title:            Thiago Thomaz
description:      Thiago Thomaz's Blog
#url: http://localhost:4000
url: http://thiagorthomaz.github.io

# Dependencies
markdown: kramdown
kramdown:
  input: GFM
highlighter:      rouge

#Configuring Permalinks
#permalink:     '/blog/:year/:title/'
permalink:   /blog/:title
#paginate_path: '/blog/page:num/'

#Adding custom directory
include: ['_pages']
relative_permalinks: false

#https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo